CREATE TABLE IF NOT EXISTS offers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    organization VARCHAR(255) DEFAULT NULL,
    role VARCHAR(100) NOT NULL,
    skills_description TEXT NOT NULL,
    category VARCHAR(100) DEFAULT NULL,
    city VARCHAR(100) NOT NULL,
    active TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE requests ADD COLUMN ai_matches TEXT DEFAULT NULL;
